### ISSUE TITLE
Enter and spacebar to open/close accordion item

### ISSUE THREAD

**Issue by robertvrabel** [Alhadis/Accordion#11]
First, thanks for the great package!

So I'm seeing code for

```js
/** Enter: Toggle */
case 13: {
    THIS.open = !THIS.open;
    break;
}
```

But this doesn't appear to be working, it does not toggle the item to be open and closed. Ideally i'd also like to have the spacebar do the same thing. The right and left arrows work as I'd expect though.

Is this behavior something that could be added? Or do you have a recommendation of adding my own event listener to accomplish this?

**Comment by Alhadis** [comment]
:wave: Hey @robertvrabel,

You're right about the space-bar: I'll make a note of adding it. For the <kbd>Enter</kbd> key, however, you *should* be able to toggle the folds when they receive focus. Can you confirm that the event is firing? Add this somewhere in the page, then press <kbd>Enter</kbd>:

~~~js
window.addEventListener("keydown", function(event){
	if(event.keyCode === 13)
		console.log("ENTER key pressed. This should be working...");
	else
		console.log("Wrong keycode! It should be " + event.keyCode);
});
~~~

If you see the first message, it's possible that something on the page is intercepting the `keydown` event and stopping it from propagating (which means it doesn't reach the `Accordion` instance...)

**Comment by robertvrabel** [comment]
@Alhadis Thanks for the response! So I did debug the code directly and I've confirmed it does get into this when I hit enter on the element. This reports `true`, but does not actually open the fold. I'm not exactly where to debug it from there but if you can point in the right direction I can keep following the code to see where its not triggering the open.

```js
/** Enter: Toggle */
case 13: {
    console.log(!THIS.open);
    THIS.open = !THIS.open;
    break;
}
```

**Comment by Alhadis** [comment]
Could you add `console.trace(THIS);` and copy+paste the resulting stack trace, please? Also, what browser/device are you witnessing this on? Is it consistent across all platforms, or something specific?

This is quite strange, and so far I'm out of theories as to why this could be happening. 🤔

**Comment by robertvrabel** [comment]
So I copied the HTML example into my page that you provide and it works. So its totally on me because I wrapped the "heading" in html link (for accessibility reasons because i'm interested in deep-linking to open one eventually). So it looks like if I add this, it works properly:

```js
/** Enter: Toggle */
case 13: {
    THIS.open = !THIS.open;
	
    if(heading.tagName === 'A') {
        heading.click();
    }

    break;
}
```

I'm not sure if this is optimal. So my question would be 1) Is there an easy way for me to add this outside the package? Or 2) Would you accept a pull request to support links as headings?

**Comment by Alhadis** [comment]
Okay, whoa, wait a second. You'll need to show me the actual DOM outline for the Accordion markup. This will probably explain everything – you can blank any body text that can't be shown for NDA reasons.

**Comment by robertvrabel** [comment]
Yes, sorry I didn't mention that at first I realize thats a big part of it :). It just worked out of the box and I noticed you were referencing the heading as `firstElement` so I thought it was good to go. Coming from anther accordion package that relied on JavaScript, we're trying to stick to the same HTML so this is what i'm using. I was able to style it to look like this:

<img width="904" alt="Screen-shot 2018-05-14 at 10:08:59 am" src="https://user-images.githubusercontent.com/634788/40002504-faa645d8-575e-11e8-8152-c766ed2e3a23.png">

```html
<ul class="accordion">
    <li>
        <a href="#panel1a">Accordion 1</a>
        <div id="panel1a" class="fold">
            <p>Panel 1. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
        </div>
    </li>
    <li>
        <a href="#panel2a">Accordion 2</a>
        <div id="panel2a" class="fold">
            <p>Panel 2. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
        </div>
    </li>
    <li>
        <a href="#panel3a">Accordion 3</a>
        <div id="panel3a"  class="fold">
            <p>Panel 3. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
        </div>
    </li>
</ul>
```

**Comment by robertvrabel** [comment]
I actually have some code that automatically applies the `class="fold"` on it as well. We try really hard to keep our markup simple because people use it in a wysiwyg editor. So we just rely on that structure and one `class="accordion"` to accomplish it.

```js
document.querySelectorAll('ul.accordion > li').forEach(function(item) {
    // Make the items absolute positioning now that we know javascript is enabled
    item.classList.add('absolute')

    // Apply the content fold
    item.querySelector('div').classList.add('fold');
});
```

**Comment by Alhadis** [comment]
Alright, we're getting there. I'm able to reproduce what's happening by replacing the accordion in `demos/anim-switch.htm` with the HTML snippet you've given above. Could you also share the CSS you're using? CSS is pivotal to the accordion's functionality (as it should be for any front-end component, IMHO).

Just curious, is there any particular reason you need the headings to link to their fold element (via use of `#panel2a` and `panel2a`)?

**EDIT:** Apologies for making all those minor edits to your posts, I can't stand seeing unhighlighted code blocks in markdown. 😁It makes my teeth itch.

**Comment by Alhadis** [comment]
Oh! Wait, of course there's a particular reason you need headings to link to stuff... you need permalinks/deep-linking to be possible. Which, I admit, is *definitely* an important addition. 😅 Surprised I didn't think of that...

**Comment by robertvrabel** [comment]
Yea here is the output, i'll provide CSS and SASS:

CSS:

```css
.accordion {
  padding: 0;
  margin-bottom: 1rem;
  position: relative;
  list-style: none;
  background: #efefef;
}

.accordion > li {
  width: 100%;
  position: absolute;
}

.accordion > li > a {
  cursor: pointer;
  -webkit-user-select: none;
     -moz-user-select: none;
      -ms-user-select: none;
          user-select: none;
  position: relative;
  display: block;
  padding: 1.25rem 1rem;
  border: 1px solid #d5d5d5;
  border-bottom: 0;
  line-height: 1;
  color: foreground(#efefef, #0c5449);
  text-decoration: none;
  font-weight: bold;
}

.accordion > li > a:first-child:hover,
.accordion > li > a:first-child:focus {
  background-color: #e6e6e6;
}

.accordion > li > a::before {
  position: absolute;
  top: 50%;
  right: 1rem;
  margin-top: -0.5rem;
  content: '+';
}

.accordion > li.open > a::before {
  content: '\2013';
}

.accordion > li > .fold {
  padding: 1rem;
  border: 1px solid #d5d5d5;
  border-top: none;
  background-color: #fff;
  color: foreground(#efefef, #0c5449);
}

.accordion > * {
  overflow: hidden;
  padding: 0;
  margin: 0;
  -webkit-transition: .3s ease all;
  transition: .3s ease all;
}
```

SCSS:

```css
.accordion {
    padding: 0;
    margin-bottom: 1rem;
    position: relative;
    list-style: none;
    background: #efefef;

    & > li {
        width: 100%;
        position: absolute;

        > a {
            cursor: pointer;
            user-select: none;
            position: relative;
            display: block;
            padding: 1.25rem 1rem;
            border: 1px solid #d5d5d5;
            border-bottom: 0;
            line-height: 1;
            color: foreground(#efefef, #0c5449);
            text-decoration: none;
            font-weight: bold;

            &:first-child:hover,
            &:first-child:focus, {
                background-color: #e6e6e6;
            }

            // Open symbol
            &::before {
                position: absolute;
                top: 50%;
                right: 1rem;
                margin-top: -0.5rem;
                content: '+';
            }
        }

        // Close symbol
        &.open > a::before {
            content: '\2013';
        }

        // Content area
        > .fold {
            padding: 1rem;
            border: 1px solid #d5d5d5;
            border-top: none;
            background-color: #fff;
            color: foreground(#efefef, #0c5449);
        }
    }

    > * {
        overflow: hidden;
        padding: 0;
        margin: 0;
        transition: 0.3s ease all;
    }
}
```
